/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
    'TriggerMRReview': ApiRouteHandler<{ mrUrl: string }, ApiResponse<200, { message: string; reviewId: string; mrUrl: string }> | ApiResponse<400, { error: string }>, { topic: 'fetch-mr-diff'; data: { reviewId: string; mrUrl: string; projectPath: string; mrIid: number } }>
    'SendReviewWebhook': EventHandler<{ reviewId: string; mrUrl: string; mrTitle: string; reviewResult: { summary: string; issues?: Array<unknown>; recommendations?: Array<string> } }, never>
    'ProcessAIReview': EventHandler<{ reviewId: string; projectPath: string; mrTitle: string; mrDescription?: string }, { topic: 'send-review-webhook'; data: { reviewId: string; mrUrl: string; mrTitle: string; reviewResult: { summary: string; issues?: Array<unknown>; recommendations?: Array<string> } } }>
    'FetchMRDiff': EventHandler<{ reviewId: string; mrUrl: string; projectPath: string; mrIid: number }, { topic: 'process-ai-review'; data: { reviewId: string; projectPath: string; mrTitle: string; mrDescription?: string } }>
  }
    
}